mysite/appengine/urls.py
from django.contrib import admin
from django.urls import include, path
from core.views import DashboardView, search
from crud import views as crud_views
from core import views as core_views
from django.conf import settings
from django.conf.urls.static import static
from registers.urls import registers_patterns
from reports.urls import reports_patterns

from django.conf import settings

urlpatterns = [
    path('', DashboardView.as_view(), name="home"),
    path('search/', core_views.search, name="search"),
    path('location/<int:id>/', core_views.location, name="location"),
    path('registers/', include(registers_patterns)),
    path('reports/', include(reports_patterns)),
    path('admin/', admin.site.urls),
    # Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]

#Custom titles for admin
admin.site.site_header = "Atopa"
admin.site.index_title = "Panel de Administrador"
admin.site.site_title = "Atopa"

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/crud/urls.py
from django.urls import path

from . import views

app_name = 'crud'
urlpatterns = [
    path('cities/', views.list_cities, name='cities'),
]

mysite/registers/urls.py
from django.urls import path
from . import views
from .views import RegisterDelete, RegisterListView, RegisterDetailView, RegisterUpdate

registers_patterns = ([
    path('', RegisterListView.as_view(), name='registers'),
    path('<int:pk>/<slug:register_slug>/', RegisterDetailView.as_view(), name='register'),
    path('create', views.register_new, name= 'create'),
    path('update/<int:pk>/', RegisterUpdate.as_view(), name= 'update'),
    path('delete/<int:pk>/', RegisterDelete.as_view(), name= 'delete'),
    path('scanner_qr/', views.scanner_qr, name='scanner_qr'),
    path('reported/<int:pk>/', views.register_reported, name='reported'),
], 'registers' )

mysite/registers/models.py
from django.db import models
#from ckeditor.fields import RichTextField
from django.conf import settings
from django.contrib.auth.models import User
from crud.models import SubCategory
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw
from .validators import valid_extension

class Register(models.Model):
    description = models.CharField(max_length=600, verbose_name="Descripción", unique=True)
    qr_code = models.ImageField(verbose_name= "", upload_to='qr_codes',null=False, blank=True,validators=[valid_extension])
    registration_date = models.DateField(auto_now_add=True, verbose_name="Fecha de Registro")
    reported = models.BooleanField(verbose_name="Reportar", default=False, help_text="Indica si el registro ha sido extraviado.")
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, default=0, verbose_name="Sub Categoría")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Usuario")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    update_date = models.DateTimeField(auto_now=True, verbose_name="Fecha de modificación")
    

    class Meta:
        verbose_name = 'Registro'
        verbose_name_plural = 'Registros'
        ordering = ['-registration_date','-user']

    def __str__(self):
        return self.description

    def save(self, *args, **kwargs):
        data = "http://127.0.0.1:8000/accounts/profile/owner/" + str(self.user.id) + "/"
        qrcode_img = qrcode.make(data)
        canvas = Image.new('RGB', (400, 400), 'white')
        canvas.paste(qrcode_img)
        fname = f'qr-{self.description}.png'
        buffer = BytesIO()
        canvas.save(buffer,'PNG')
        self.qr_code.save(fname, File(buffer), save=False)
        canvas.close()
        super().save(*args, **kwargs)

mysite/reports/models.py
from email.policy import default
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from crud.models import TypeReport, SubCategory
from registers.models import Register
from django.db import models
from encrypted_model_fields.fields import EncryptedCharField

class Report(models.Model):
    day  = timezone.now()
    hour = timezone.now()
    formatedDay  = day.strftime("%Y-%m-%d")
    formatedHour = hour.strftime("%H:%M")
    description = models.CharField(max_length=600, verbose_name="Descripción", unique=True)
    found_date = models.DateField(verbose_name="Fecha", default=formatedDay)
    found_time = models.TimeField(verbose_name="Hora", default=formatedHour)
    image = models.ImageField(verbose_name="Imagen", upload_to='reports', default=None)
    status = models.BooleanField(verbose_name="Activo", default=True, help_text="Indica si el registro está Activo o Inactivo.")
    type_report = models.ForeignKey(TypeReport, on_delete=models.CASCADE, default=0, verbose_name="Tipo de Reporte")
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, default=0, verbose_name="Sub Categoría")
    reward = EncryptedCharField(max_length=100, verbose_name="Recompensa", blank=True)
    coord_latitude = models.CharField(verbose_name="Coordenada Latitud", max_length=50)
    coord_length = models.CharField(verbose_name="Coordenada Longitud",max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Usuario")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    update_date = models.DateTimeField(auto_now=True, verbose_name="Fecha de modificación")
    register  = models.CharField(verbose_name="Registro", blank=True, max_length=50)
    

    class Meta:
        verbose_name = 'Reporte'
        verbose_name_plural = 'Reportes'
        ordering = ['-create_date']

    def __str__(self):
        return self.description

    

mysite/registers/forms.py
from django import forms
from django.forms import models
from django.forms.forms import Form
from .models import Register
from django.contrib.admin import widgets

    
class RegisterForm(forms.ModelForm):
    class Meta:
        model = Register
        fields = ['sub_category','description']
        widgets = {
            'description': forms.TextInput(attrs={'class':'form-control mb-2 mt-3', 'placeholder':'Ingrese una descripción'}),
            'sub_category': forms.Select(attrs={'class':'form-control mb-2 mt-3'}),
        }

class UploadFileForm(forms.Form):
    file = forms.FileField(required=False)

class QrForm(forms.ModelForm):
    class Meta:
            model = Register
            fields = ['qr_code']

mysite/registers/views.py
from os import name
import django
from django.contrib.admin.views import decorators
from .models import Register
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import redirect, render, HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from django import forms
from six import BytesIO
from .forms import QrForm, RegisterForm
from pyzbar.pyzbar import decode
from PIL import Image
from flask import Flask, render_template, request
from reports.forms import ReportForm

# Create your views here.
class RegisterListView(ListView):
    template_name= 'registers/register_list.html'
    paginate_by = 5
    
    def get_queryset(self, *args, **kwargs):
        return Register.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Lista de Registros'

        return context

class RegisterDetailView(DetailView):
    model = Register


def register_new(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            print("entro register")
            return redirect('registers:registers')
    else:
        form = RegisterForm()
        print("entro 2 register")
    return render(request, 'registers/register_form.html', {'form': form})
    

class RegisterUpdate(UpdateView):
    model = Register
    fields = ['sub_category', 'description']
    template_name_suffix = '_update_form'
    
    def get_form(self, form_class=None):
        form = super(RegisterUpdate, self).get_form()
        # Modificar en tiempo reald
        form.fields['description'].widget = forms.TextInput(attrs={'class':'form-control mb-2 mt-3', 'placeholder':'Ingrese una descripción'})
        return form

    def get_success_url(self) -> str:
        return reverse_lazy('registers:update', args=[self.object.id]) + '?ok'

def register_reported(request, pk):
    register = Register.objects.filter(id=pk)
    if request.method == "POST":
        form = ReportForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            Register.objects.filter(id=pk).update(reported=True)
            return redirect('registers:registers')
    else:
        form = ReportForm()
        print("entro 2")
    return render(request, 'registers/register_reported.html', {'form': form, 'register': register})

class RegisterDelete(DeleteView):
    model = Register
    success_url = reverse_lazy('registers:registers')

    
def scanner_qr(request):
    if request.method == 'POST':
        formulario = QrForm(request.POST, request.FILES)
        if formulario.is_valid():
            ruta_qr = request.FILES.get('qr_code')
            d = decode(Image.open(ruta_qr))
            if (len(d)>0):
                read_qr = d[0].data.decode("ascii")
                result = ""
            else:
                read_qr = ""
                result = "La imagen no puede ser escaneada. Verifique que sea un Código QR."
            return render(request,"registers/scanner_qr_form.html", {'form': formulario, 'read_qr': read_qr,'result': result})
    else:
        formulario = QrForm()
    return render(request, "registers/scanner_qr_form.html",{'form': formulario})

mysite/registers/templates/registers/register_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Eliminar Registro{% endblock %}
{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}
{% block headers %}
    <h1 style="text-align: center;">Registro</h1>
{% endblock %}
{% block content %}
<div class="col-11 text-right">
  <a href="{% url 'registers:registers' %}"><button type="button" class="btn btn-primary" ><i class="fa fa-fw fa-angle-double-left "></i> Regresar</button></a>
</div>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Está seguro de que desea eliminar "{{ object }}"?</p>
                <input type="submit" class="btn btn-primary btn-block mb-2 mt-2" value="Sí, eliminar el Registro" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

mysite/registers/templates/registers/register_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Registros{% endblock %}
{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}
{% block headers %}
    <h1 style="text-align: center;">Registros</h1>
{% endblock %}
{% block content %}
{% include 'registers/includes/register_menu.html' %}
<main role="main">
  <div class="container">
        <div>
         <h2>{{ register.description}}</h2>
            <p><a href="{% url 'registers:update' register.id %}">Editar</a></p>
        </div>
  </div>
</main>
{% endblock %}

mysite/registers/templates/registers/register_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear Registro{% endblock %}

{% block headers %}
  <h2 style="text-align: center;">Registros</h2>
{% endblock %}
{% block content %}
{% comment %} {% include 'registers/includes/register_menu.html'%} {% endcomment %}
<main role="main">
  <div class="container">
    <div class="col-md-10 mx-auto text-right">
      <a href="{% url 'registers:registers' %}"><button type="button" class="btn btn-primary" ><i class="fa fa-fw fa-angle-double-left "></i> Regresar</button></a>
    </div>
    <div class="row mt-3 mb-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
              <p for="{{form.sub_category.id_for_label}}"><b>{{form.sub_category.label}}</b></p>
              {{form.sub_category}}
              <p for="{{form.description.id_for_label}}"><b>{{form.description.label}}</b></p>
              {{form.description}}
              <div class="text-center">
                <input type="submit" class="btn btn-primary btn-block mb-2 mt-2" value="Crear Registro"/>
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

mysite/registers/templates/registers/register_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Registros{% endblock %}
{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}
{% block headers %}
    <h1 style="text-align: center;">Registros</h1>
{% endblock %}
{% block content %}
<main role="main">
  <div class="container mb-4">
      <a href="{% url 'registers:create' %}"><button type="button" class="btn btn-primary"><i class="fa fa-fw fa-plus "></i> Crear Registro</button></a>
      <div class="table-responsive-sm">  
        <table class="table table-hover mt-3">
        <thead>
          <tr>
            <th scope="col">Fecha de Registro</th>
            <th scope="col">Categoría</th>
            <th scope="col">Sub Categoría</th>
            <th scope="col">Descripción</th>
            <th scope="col">QR</th>
            <th scope="col">Descargar QR</th>
            <th scope="col">Editar</th>
            <th scope="col">Eliminar</th>
            <th scope="col">Reportar</th>
          </tr>
        </thead>
        <tbody>
          {% for register in register_list|dictsort:"id" %}
          {% if user == register.user %}
          <tr>
            <td>{{ register.registration_date|date:'d/m/Y'}}</td>
            <td>{{ register.sub_category.category.description}}</td>
            <td>{{ register.sub_category.description}}</td>
            <td>{{ register.description}}</td>
            <td>{% if register.qr_code %}<img src="{{ register.qr_code.url }}" class="img-fluid">{% endif %}</td>
            <td><a onclick="downloadFile('{{ register.qr_code.url }}');" ><button type="button" class="btn btn-primary" id="btn" title="Descargar QR"><i class="fa fa-fw fa-download"></i></button></a></td>
            <td><a href="{% url 'registers:update' register.id %}"><button type="button" class="btn btn-secondary" title="Editar">Editar <i class="fa fa-fw fa-edit"></i></button></a></td>
            <td><a href="{% url 'registers:delete' register.id %}"><button type="button" class="btn btn-danger" title="Elminar">Eliminar<i class="fa fa-fw fa-trash"></i></button></a></td> 
            <td>{% if register.reported == True %}<input name="reported" type="checkbox" checked="checked" style="transform: scale(2);" readonly="readonly" onclick="javascript: return false;"/>{% else %}<input name="reported" type="checkbox" style="transform: scale(2);" readonly="readonly" onclick="javascript: return false;"/> <a href="{% url 'registers:reported' register.id %}" class="mb-2 mt-2 ml-2"> Ir </a>{% endif %} </td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
        </table>
      </div>
    
    <!-- Menú de paginación -->
    {% if is_paginated %}
      <div class="mt-3">
        <ul class="pagination justify-content-center">

          {% if page_obj.has_previous %}
            <li class="page-item">
              <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a href="#" class="page-link">&laquo;</a>
            </li>
          {% endif %}

          {% for i in paginator.page_range %}
              <li class="page-item {% if page_obj.number == i %} active {% endif %}">
                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
              </li>
          {% endfor %}

          {% if page_obj.has_next %}
            <li class="page-item">
              <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a href="#" class="page-link">&raquo;</a>
            </li>
          {% endif %}
        </ul>
      </div>
    {% endif %}

  </div>
</main>

<script>
  function downloadFile(filePath){
    var link=document.createElement('a');
    link.href = filePath;
    link.download = filePath.substr(filePath.lastIndexOf('/') + 1);
    link.click();
  }

</script>

{% endblock %}

mysite/registers/templates/registers/register_reported.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Reportar{% endblock %}
{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}
{% block headers %}
    <h1 style="text-align: center;">Reportar</h1>
{% endblock %}
{% block content %}
<div class="col-11 text-right">
  <a href="{% url 'registers:registers' %}"><button type="button" class="btn btn-primary" ><i class="fa fa-fw fa-angle-double-left "></i> Regresar</button></a>
</div>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          <form action="" method="post" enctype="multipart/form-data">{% csrf_token %} 
                <p>{{result}}</p>
                {% for register in register%}
                <p for="{{form.type_report.id_for_label}}"><b>{{form.type_report.label}}</b></p>
                {{form.type_report.errors}}
                <select name="type_report" class="form-control mb-2 mt-3" id="id_type_report">
                  <option value="2">Extraviado</option>
                </select>
                <p for="{{form.sub_category.id_for_label}}"><b>{{form.sub_category.label}}</b></p>
                {{form.sub_category.errors}}
                <select name="sub_category" class="form-control mb-2 mt-3" id="id_sub_category">
                  <option value="{{register.sub_category.id}}">{{register.sub_category}}</option>
                </select>
                <p for="{{form.description.id_for_label}}"><b>{{form.description.label}}</b></p>
                {{form.description.errors}}
                <input id="description" type="text" name="description" class="form-control" value="{{ register.description }}">
                <p for="{{form.found_date.id_for_label}}"><b>{{form.found_date.label}}</b></p>
                {{form.found_date.errors}}
                {{form.found_date}}
                <p for="{{form.found_time.id_for_label}}"><b>{{form.found_time.label}}</b></p>
                {{form.found_time.errors}}
                {{form.found_time}}
                <p for="{{form.image.id_for_label}}"><b>{{form.image.label}}</b></p>
                {{form.image.errors}}
                {{form.image}}   
                <br><input style="opacity:1;" type="checkbox" data-required="1" name="reward" id="reward" class="mb-3 mt-4"> <i>Desea realizar una recompensa?</i><br>  
                <p for="{{form.reward.id_for_label}}" id="tr_reward" style="display:none;"><b>{{form.reward.label}}</b> {{form.reward}}</p><br>
                <p for="{{form.coord_latitude.id_for_label}}"><b>{{form.coord_latitude.label}}</b></p>
                {{form.coord_latitude.errors}}
                {{form.coord_latitude}}
                <p for="{{form.coord_length.id_for_label}}"><b>{{form.coord_length.label}}</b></p>
                {{form.coord_length.errors}}
                {{form.coord_length}}
                <label for="{{form.status.id_for_label}}"><b>{{form.status.label}}</b></label></p>
                {{form.status.errors}}
                {{form.status}} {{form.status.help_text}}
                <input type="text" name="register" class="form-control mb-2 mt-2" maxlength="50" id="id_register" value="{{ register.id }}" style="display: none;">
                {% endfor %}
            <br>
            
            <div id="mapa" class="capas">
            </div>
            <input type="submit" class="btn btn-primary btn-block mb-2 mt-3" value="Reportar" />
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

mysite/registers/templates/registers/register_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar Registro{% endblock %}
{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}
{% block headers %}
    <h1 style="text-align: center;">Registro</h1>
{% endblock %}
{% block content %}
<div class="col-11 text-right">
  <a href="{% url 'registers:registers' %}"><button type="button" class="btn btn-primary" ><i class="fa fa-fw fa-angle-double-left "></i> Regresar</button></a>
</div>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          {% if 'ok' in request.GET %}
            <p style="color:green;"> Se ha actualizado correctamente.</p>
          {% endif %} 
          <form action="" method="post">{% csrf_token %}
            <p for="{{form.sub_category.id_for_label}}" class="mb-2 mt-2"><b>{{form.sub_category.label}}</b></p>
            {{form.sub_category}}
            <p for="{{form.description.id_for_label}}" class="mb-2 mt-2"><b>{{form.description.label}}</b></p>
            {{form.description}}
            <input type="submit" class="btn btn-primary btn-block mb-2 mt-2" value="Actualizar" />
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

mysite/registers/templates/registers/scanner_qr_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Escanear QR{% endblock %}
{% block headers %}
  <h2 style="text-align: center;">Escanear Código QR</h2>
  {% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-3">
      <div class="col-md-9 mx-auto">
        <div>
            <p style="color:red">{{ result }}</p>
            <form action="" method="post" id="f_scan" enctype="multipart/form-data">{% csrf_token %}
                  {{ form.as_table }}
                  <input type="submit" class="form-control btn btn-primary mt-3" value="Escanear" name="btn_escanear" id="btn_escanear">
                <br>
                <label for="read" class="mb-1 mt-3">Resultado Obtenido:</label>
                <a href="{{ read_qr }}" id="read" class="form-control mb-3 mt-3">{{ read_qr }}</a>
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}